AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: API Gateway to EventBridge proxy. Translates full events to the EventBus.

Parameters:
  CustomFunctionName:
    Type: String
    Default: quip_nugget_app
  Stage:
    Type: String
    Default: dev
  CustomTableName:
    Type: String
    Default: quip_nugget_data_analytics

Conditions:
  isProd: !Equals [ !Ref Stage, prod ]

Resources:
  LambdaQuipNuggetApp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !If [ isProd, !Sub "${CustomFunctionName}", !Sub "${Stage}_${CustomFunctionName}" ]
      CodeUri: src/
      Description: ApiGW to lambda
      Handler: app.lambda_handler
      MemorySize: 256
      PackageType: Zip
      Runtime: python3.11
      Timeout: 300
      Tracing: Active

      Policies:
        - SSMParameterReadPolicy:
            ParameterName: 'OPENAI_API_KEY'
        - SNSPublishMessagePolicy:
            TopicName: !If [ isProd, "quip-nugget-analytics", !Sub "${Stage}-quip-nugget-analytics" ]
        - DynamoDBCrudPolicy:
            TableName: !If [ isProd, !Sub "${CustomTableName}", !Sub "${Stage}_${CustomTableName}" ]
#        - EventBridgePutEventsPolicy:
#            EventBusName: default
      Layers:
        - !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:sosw:1"
      Tags:
        Env: !Ref Stage

  FunctionResourcePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: apigateway.amazonaws.com
      FunctionName: !Ref LambdaQuipNuggetApp
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*'

