AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Quip Nugget analytics table

Parameters:
  CustomTableName:
    Type: String
    Default: quip_nugget_data_analytics
  Stage:
    Type: String
    Default: prod


Conditions:
  isProd: !Equals [ !Ref Stage, 'prod' ]

Resources:
  QuipNuggetAnalyticsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [ isProd, !Sub "${CustomTableName}", !Sub "${Stage}_${CustomTableName}" ]
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "user_input"
          AttributeType: "S"
        - AttributeName: "created_at"
          AttributeType: "N"

      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      GlobalSecondaryIndexes:
        - IndexName: "user_input"
          KeySchema:
            - AttributeName: "user_input"
              KeyType: "HASH"
            - AttributeName: "created_at"
              KeyType: "RANGE"



          Projection:
            ProjectionType: "ALL"

#      StreamSpecification:
#        StreamViewType: "NEW_AND_OLD_IMAGES"

#Outputs:
#  TableStreamArn:
#    Value: !GetAtt SoswFormRecordsDDBTable.StreamArn
#    Export:
#      Name: StreamArn
