version = 0.1

[default.deploy.parameters]
stack_name = "dev-qn_collect_day_analytics"
s3_prefix = "dev-qn_collect_day_analytics"
parameter_overrides = "Stage=\"dev\""
region = "us-west-2"
resolve_s3 = true
source = "src/"
confirm_changeset = false
force-upload = true
capabilities = "CAPABILITY_IAM"

[prod.deploy.parameters]
stack_name = "qn_collect_day_analytics"
s3_prefix = "qn_collect_day_analytics"
parameter_overrides = "Stage=\"prod\""
region = "us-west-2"
resolve_s3 = true
source = "src/"
confirm_changeset = true
force-upload = true
capabilities = "CAPABILITY_IAM"
